# Set the minimum supported Rust version
msrv = "1.70"

# Lint thresholds
cognitive-complexity-threshold = 10
too-many-arguments-threshold = 3
too-many-lines-threshold = 300
type-complexity-threshold = 200
enum-variant-name-threshold = 20
